/* The following code was generated by JFlex 1.7.0 */

package model.services;

import gui.MainViewController;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>C:/Users/tomas/Documents/eclipse-workspace-javaFX/projetoAutomatos/src/model/services/language.lex</tt>
 */
public class LexicalAnalyzer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\44\1\43\1\5\1\5\1\5\22\0\1\47\4\0\1\41"+
    "\2\0\1\34\1\35\1\37\1\36\1\3\1\27\2\0\1\6\1\2"+
    "\1\46\7\2\1\40\1\0\1\32\1\33\1\42\2\0\32\1\4\0"+
    "\1\1\1\0\1\15\1\1\1\11\1\1\1\23\1\13\1\17\1\30"+
    "\1\7\2\1\1\16\1\14\1\10\1\12\1\24\1\25\1\20\1\22"+
    "\1\21\1\26\1\31\4\1\1\45\1\4\1\45\7\0\1\5\u1fa2\0"+
    "\1\5\1\5\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\12\3\1\4\1\3\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\2\20\1\21\3\3\1\22\4\3\1\23\2\3\1\4"+
    "\21\3\1\4\4\3\1\24\1\22\1\3\1\0\1\25"+
    "\1\26\1\27\1\3\1\23\4\3\1\30\5\3\3\0"+
    "\3\3\1\31\1\25\4\3\1\1\4\3\1\32\3\0"+
    "\12\3\1\33\2\3\4\0\3\3\1\34\1\35\2\3"+
    "\1\36\1\3\3\0\1\32\1\37\5\3\4\0\5\3"+
    "\4\0\4\3\1\0\1\32\1\0\2\32\2\0\1\3"+
    "\2\0\1\3\2\0\1\3\5\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[174];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\50\0\120\0\170\0\50\0\240\0\310\0\360"+
    "\0\u0118\0\u0140\0\u0168\0\u0190\0\u01b8\0\u01e0\0\u0208\0\u0230"+
    "\0\u0258\0\u0280\0\u02a8\0\u02d0\0\u02f8\0\u0320\0\u0348\0\u0370"+
    "\0\u0398\0\u03c0\0\u03e8\0\u0410\0\u0438\0\u0460\0\u0488\0\u04b0"+
    "\0\u04d8\0\u0500\0\u0528\0\u0550\0\u0578\0\u05a0\0\u05c8\0\u05f0"+
    "\0\u0618\0\u0640\0\u0668\0\u0690\0\u06b8\0\u06e0\0\u0708\0\u0730"+
    "\0\u0758\0\u0780\0\u07a8\0\u07d0\0\u07f8\0\u0820\0\u0848\0\u0870"+
    "\0\u0898\0\u08c0\0\u08e8\0\u0910\0\u0938\0\u0960\0\u0988\0\u09b0"+
    "\0\u09d8\0\u0a00\0\u0a28\0\u0a50\0\u0a78\0\u0aa0\0\u0ac8\0\u0af0"+
    "\0\u0b18\0\u0b40\0\u0b68\0\u0b90\0\u0bb8\0\u0be0\0\u0c08\0\u0c30"+
    "\0\u0c58\0\u0c80\0\u0ca8\0\u0cd0\0\u0cf8\0\u0d20\0\u0d48\0\u0d70"+
    "\0\u0d98\0\u0dc0\0\u0de8\0\u0e10\0\u0e38\0\u0e60\0\u0e88\0\u0eb0"+
    "\0\u0ed8\0\u0f00\0\u0f28\0\u0f50\0\u0f78\0\u0fa0\0\u0fc8\0\u0ff0"+
    "\0\u1018\0\u1040\0\u1068\0\u1090\0\u10b8\0\u10e0\0\u1108\0\u1130"+
    "\0\u1158\0\u1180\0\u11a8\0\u11d0\0\u11f8\0\u1220\0\u1248\0\u1270"+
    "\0\u1298\0\u12c0\0\u12e8\0\u1310\0\u1338\0\u1360\0\u1388\0\u13b0"+
    "\0\u13d8\0\u1400\0\u1428\0\u1450\0\u1478\0\u14a0\0\u14c8\0\u14f0"+
    "\0\u1518\0\u1540\0\u1568\0\u1590\0\u15b8\0\u15e0\0\u1608\0\u1630"+
    "\0\u1658\0\u1680\0\u16a8\0\u16d0\0\u16f8\0\u1720\0\u1748\0\u1770"+
    "\0\u1798\0\u17c0\0\u17e8\0\u1810\0\u1838\0\u1860\0\u1888\0\u18b0"+
    "\0\u18d8\0\u1900\0\u1928\0\u1950\0\u1978\0\u19a0\0\u19c8\0\u19f0"+
    "\0\u1a18\0\u1a40\0\u1a68\0\u1a90\0\u1ab8\0\u1ae0";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[174];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\2\1\3\1\0\1\5\1\6"+
    "\1\3\1\7\1\10\1\11\2\3\1\12\1\3\1\13"+
    "\1\3\1\14\1\15\1\16\2\3\1\17\2\3\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\51\0\2\35\1\0"+
    "\1\35\1\0\21\35\1\0\2\35\14\0\1\35\3\0"+
    "\1\4\3\0\1\4\37\0\1\4\2\0\2\35\1\0"+
    "\1\35\1\0\2\35\1\36\16\35\1\0\2\35\14\0"+
    "\1\35\2\0\2\35\1\0\1\35\1\0\7\35\1\37"+
    "\11\35\1\0\2\35\14\0\1\35\2\0\2\35\1\0"+
    "\1\35\1\0\20\35\1\40\1\0\2\35\14\0\1\35"+
    "\2\0\2\35\1\0\1\35\1\0\1\35\1\41\5\35"+
    "\1\42\11\35\1\0\2\35\14\0\1\35\2\0\2\35"+
    "\1\0\1\35\1\0\15\35\1\43\3\35\1\0\2\35"+
    "\14\0\1\35\2\0\2\35\1\0\1\35\1\0\15\35"+
    "\1\44\3\35\1\0\2\35\14\0\1\35\2\0\2\35"+
    "\1\0\1\35\1\0\15\35\1\45\3\35\1\0\2\35"+
    "\14\0\1\35\2\0\2\35\1\0\1\35\1\0\2\35"+
    "\1\46\11\35\1\47\1\50\3\35\1\0\2\35\14\0"+
    "\1\35\2\0\2\35\1\0\1\35\1\0\7\35\1\51"+
    "\11\35\1\0\2\35\14\0\1\35\30\0\1\17\2\0"+
    "\1\17\50\0\1\20\50\0\1\21\50\0\1\22\50\0"+
    "\1\23\50\0\1\24\50\0\1\25\50\0\1\26\50\0"+
    "\1\27\50\0\1\30\50\0\1\31\2\32\45\0\3\32"+
    "\3\0\1\4\3\0\1\4\35\0\2\32\1\33\50\0"+
    "\1\34\1\0\2\52\1\53\1\35\1\0\21\52\1\0"+
    "\2\52\6\0\1\53\5\0\1\52\2\0\2\52\1\53"+
    "\1\35\1\0\1\52\1\54\11\52\1\55\5\52\1\0"+
    "\2\52\6\0\1\53\5\0\1\52\2\0\2\52\1\53"+
    "\1\35\1\0\12\52\1\56\1\52\1\57\4\52\1\0"+
    "\2\52\6\0\1\53\5\0\1\52\2\0\2\52\1\53"+
    "\1\35\1\0\4\52\1\60\14\52\1\0\2\52\6\0"+
    "\1\53\5\0\1\52\2\0\2\52\1\53\1\35\1\0"+
    "\6\52\1\61\12\52\1\0\2\52\6\0\1\53\5\0"+
    "\1\52\2\0\2\52\1\53\1\35\1\0\3\52\1\62"+
    "\15\52\1\0\2\52\6\0\1\53\5\0\1\52\2\0"+
    "\2\52\1\53\1\35\1\0\1\52\1\63\17\52\1\0"+
    "\2\52\6\0\1\53\5\0\1\52\2\0\2\52\1\53"+
    "\1\35\1\0\7\52\1\64\11\52\1\0\2\52\6\0"+
    "\1\53\5\0\1\52\2\0\2\52\1\53\1\35\1\0"+
    "\2\52\1\65\11\52\1\66\4\52\1\0\2\52\6\0"+
    "\1\53\5\0\1\52\2\0\2\52\1\53\1\35\1\0"+
    "\13\52\1\67\3\52\1\70\1\52\1\0\2\52\6\0"+
    "\1\53\5\0\1\52\2\0\2\52\1\53\1\35\1\0"+
    "\3\52\1\71\15\52\1\0\2\52\6\0\1\53\5\0"+
    "\1\52\2\0\2\52\1\53\1\35\1\0\15\52\1\72"+
    "\3\52\1\0\2\52\6\0\1\53\5\0\1\52\2\0"+
    "\2\52\1\53\1\35\1\0\12\52\1\73\6\52\1\0"+
    "\2\52\6\0\1\53\5\0\1\52\2\0\2\52\1\0"+
    "\1\52\1\0\21\52\1\0\2\52\14\0\1\52\4\0"+
    "\2\53\33\0\1\53\10\0\2\52\1\0\1\52\1\0"+
    "\3\52\1\74\15\52\1\0\2\52\14\0\1\52\2\0"+
    "\2\52\1\0\1\52\1\0\15\52\1\75\3\52\1\0"+
    "\2\52\14\0\1\52\2\0\2\52\1\0\1\52\1\0"+
    "\7\52\1\76\11\52\1\0\2\52\14\0\1\52\2\0"+
    "\2\52\1\0\1\52\1\0\4\52\1\77\14\52\1\0"+
    "\2\52\14\0\1\52\2\0\2\52\1\0\1\52\1\0"+
    "\20\52\1\100\1\0\2\52\14\0\1\52\2\0\2\52"+
    "\1\0\1\52\1\0\7\52\1\101\11\52\1\102\2\52"+
    "\14\0\1\52\2\0\2\52\1\0\1\52\1\0\7\52"+
    "\1\103\11\52\1\0\2\52\14\0\1\52\2\0\2\52"+
    "\1\0\1\52\1\0\7\52\1\104\11\52\1\0\2\52"+
    "\14\0\1\52\2\0\2\52\1\0\1\52\1\0\10\52"+
    "\1\105\10\52\1\0\2\52\14\0\1\52\2\0\2\52"+
    "\1\0\1\52\1\0\7\52\1\106\11\52\1\0\2\52"+
    "\14\0\1\52\2\0\2\52\1\0\1\52\1\0\15\52"+
    "\1\107\3\52\1\0\2\52\14\0\1\52\2\0\2\52"+
    "\1\0\1\52\1\0\7\52\1\110\11\52\1\0\2\52"+
    "\14\0\1\52\2\0\2\52\1\0\1\52\1\0\20\52"+
    "\1\111\1\0\2\52\14\0\1\52\2\0\2\52\1\0"+
    "\1\52\1\0\4\52\1\112\5\52\1\113\6\52\1\0"+
    "\2\52\14\0\1\52\2\0\2\52\1\0\1\52\1\0"+
    "\15\52\1\72\3\52\1\0\2\52\14\0\1\52\2\0"+
    "\2\52\1\0\1\52\1\0\7\52\1\114\11\52\1\0"+
    "\2\52\14\0\1\52\2\0\2\52\1\0\1\52\1\0"+
    "\1\52\1\115\17\52\1\0\2\52\14\0\1\52\2\0"+
    "\2\52\1\0\1\52\1\0\1\52\1\116\17\52\1\0"+
    "\2\52\14\0\1\52\2\0\2\52\1\0\1\52\1\0"+
    "\3\52\1\117\15\52\1\0\2\52\14\0\1\52\2\0"+
    "\2\52\1\0\1\52\1\0\3\52\1\120\15\52\1\0"+
    "\2\52\14\0\1\52\2\0\2\52\1\0\1\52\1\0"+
    "\4\52\1\60\14\52\1\0\2\52\14\0\1\52\2\0"+
    "\2\52\1\0\1\52\1\0\10\52\1\121\10\52\1\0"+
    "\2\52\14\0\1\52\23\0\1\122\1\123\1\124\24\0"+
    "\2\52\1\0\1\52\1\0\5\52\1\125\13\52\1\0"+
    "\2\52\14\0\1\52\2\0\2\52\1\0\1\52\1\0"+
    "\10\52\1\126\10\52\1\0\2\52\14\0\1\52\2\0"+
    "\2\52\1\0\1\52\1\0\12\52\1\127\6\52\1\0"+
    "\2\52\14\0\1\52\2\0\2\52\1\0\1\52\1\0"+
    "\4\52\1\130\14\52\1\0\2\52\14\0\1\52\2\0"+
    "\2\52\1\0\1\52\1\0\14\52\1\66\4\52\1\0"+
    "\2\52\14\0\1\52\2\0\2\52\1\0\1\52\1\0"+
    "\4\52\1\131\14\52\1\0\2\52\14\0\1\52\2\0"+
    "\2\52\1\0\1\52\1\0\7\52\1\132\11\52\1\0"+
    "\2\52\14\0\1\52\2\0\2\52\1\0\1\52\1\0"+
    "\10\52\1\133\10\52\1\0\2\52\14\0\1\52\2\0"+
    "\2\52\1\0\1\52\1\0\15\52\1\134\3\52\1\0"+
    "\2\52\14\0\1\52\2\0\2\52\1\0\1\52\1\0"+
    "\16\52\1\135\2\52\1\0\2\52\14\0\1\52\2\0"+
    "\2\52\1\0\1\52\1\0\4\52\1\136\14\52\1\0"+
    "\2\52\14\0\1\52\2\0\2\52\1\0\1\52\1\0"+
    "\12\52\1\137\6\52\1\0\2\52\14\0\1\52\2\0"+
    "\2\52\1\0\1\52\1\0\13\52\1\140\5\52\1\0"+
    "\2\52\14\0\1\52\2\0\2\52\1\0\1\52\1\0"+
    "\7\52\1\141\11\52\1\0\2\52\14\0\1\52\2\0"+
    "\2\52\1\0\1\52\1\0\11\52\1\142\7\52\1\0"+
    "\2\52\14\0\1\52\24\0\1\143\34\0\1\144\11\0"+
    "\1\145\42\0\1\146\33\0\2\52\1\0\1\52\1\0"+
    "\7\52\1\147\11\52\1\0\2\52\14\0\1\52\2\0"+
    "\2\52\1\0\1\52\1\0\15\52\1\150\3\52\1\0"+
    "\2\52\14\0\1\52\2\0\2\52\1\0\1\52\1\0"+
    "\15\52\1\151\3\52\1\0\2\52\14\0\1\52\2\0"+
    "\2\52\1\0\1\52\1\0\14\52\1\152\4\52\1\0"+
    "\2\52\14\0\1\52\2\0\2\52\1\0\1\52\1\0"+
    "\15\52\1\153\3\52\1\0\2\52\14\0\1\52\2\0"+
    "\2\52\1\0\1\52\1\0\2\52\1\154\16\52\1\0"+
    "\2\52\14\0\1\52\2\0\2\52\1\0\1\52\1\0"+
    "\21\52\1\0\1\155\1\52\14\0\1\52\2\0\2\52"+
    "\1\0\1\52\1\0\21\52\1\0\1\52\1\156\14\0"+
    "\1\52\2\0\2\52\1\0\1\52\1\0\7\52\1\157"+
    "\11\52\1\0\2\52\14\0\1\52\2\0\2\52\1\0"+
    "\1\52\1\0\1\52\1\160\17\52\1\0\2\52\14\0"+
    "\1\52\2\0\2\52\1\0\1\52\1\0\4\52\1\161"+
    "\14\52\1\0\2\52\14\0\1\52\2\0\2\52\1\0"+
    "\1\52\1\0\15\52\1\162\3\52\1\0\2\52\14\0"+
    "\1\52\2\0\2\52\1\0\1\52\1\0\14\52\1\57"+
    "\4\52\1\0\2\52\14\0\1\52\2\0\2\52\1\0"+
    "\1\52\1\0\4\52\1\163\14\52\1\0\2\52\14\0"+
    "\1\52\14\0\1\164\61\0\1\165\33\0\1\166\56\0"+
    "\1\167\30\0\2\52\1\0\1\52\1\0\3\52\1\62"+
    "\15\52\1\0\2\52\14\0\1\52\2\0\2\52\1\0"+
    "\1\52\1\0\1\52\1\63\17\52\1\0\2\52\14\0"+
    "\1\52\2\0\2\52\1\0\1\52\1\0\7\52\1\64"+
    "\11\52\1\0\2\52\14\0\1\52\2\0\2\52\1\0"+
    "\1\52\1\0\15\52\1\170\3\52\1\0\2\52\14\0"+
    "\1\52\2\0\2\52\1\0\1\52\1\0\2\52\1\171"+
    "\16\52\1\0\2\52\14\0\1\52\2\0\2\52\1\0"+
    "\1\52\1\0\13\52\1\172\5\52\1\0\2\52\14\0"+
    "\1\52\2\0\2\52\1\0\1\52\1\0\7\52\1\173"+
    "\11\52\1\0\2\52\14\0\1\52\2\0\2\52\1\0"+
    "\1\52\1\0\7\52\1\174\11\52\1\0\2\52\14\0"+
    "\1\52\2\0\2\52\1\0\1\52\1\0\12\52\1\73"+
    "\6\52\1\0\2\52\14\0\1\52\2\0\2\52\1\0"+
    "\1\52\1\0\2\52\1\175\16\52\1\0\2\52\14\0"+
    "\1\52\2\0\2\52\1\0\1\52\1\0\1\52\1\176"+
    "\17\52\1\0\2\52\14\0\1\52\2\0\2\52\1\0"+
    "\1\52\1\0\12\52\1\177\6\52\1\0\2\52\14\0"+
    "\1\52\2\0\2\52\1\0\1\52\1\0\12\52\1\200"+
    "\6\52\1\0\2\52\14\0\1\52\10\0\1\201\66\0"+
    "\1\202\33\0\1\203\52\0\1\204\33\0\2\52\1\0"+
    "\1\52\1\0\2\52\1\65\16\52\1\0\2\52\14\0"+
    "\1\52\2\0\2\52\1\0\1\52\1\0\13\52\1\67"+
    "\5\52\1\0\2\52\14\0\1\52\2\0\2\52\1\0"+
    "\1\52\1\0\4\52\1\205\14\52\1\0\2\52\14\0"+
    "\1\52\2\0\2\52\1\0\1\52\1\0\15\52\1\206"+
    "\3\52\1\0\2\52\14\0\1\52\2\0\2\52\1\0"+
    "\1\52\1\0\15\52\1\207\3\52\1\0\2\52\14\0"+
    "\1\52\2\0\2\52\1\0\1\52\1\0\1\52\1\54"+
    "\17\52\1\0\2\52\14\0\1\52\2\0\2\52\1\0"+
    "\1\52\1\0\2\52\1\210\16\52\1\0\2\52\14\0"+
    "\1\52\2\0\2\52\1\0\1\52\1\0\3\52\1\211"+
    "\15\52\1\0\2\52\14\0\1\52\2\0\2\52\1\0"+
    "\1\52\1\0\1\52\1\212\17\52\1\0\2\52\14\0"+
    "\1\52\15\0\1\213\50\0\1\214\50\0\1\215\44\0"+
    "\1\216\35\0\2\52\1\0\1\52\1\0\15\52\1\217"+
    "\3\52\1\0\2\52\14\0\1\52\2\0\2\52\1\0"+
    "\1\52\1\0\14\52\1\220\4\52\1\0\2\52\14\0"+
    "\1\52\2\0\2\52\1\0\1\52\1\0\14\52\1\221"+
    "\4\52\1\0\2\52\14\0\1\52\2\0\2\52\1\0"+
    "\1\52\1\0\13\52\1\55\5\52\1\0\2\52\14\0"+
    "\1\52\2\0\2\52\1\0\1\52\1\0\7\52\1\222"+
    "\11\52\1\0\2\52\14\0\1\52\2\0\2\52\1\0"+
    "\1\52\1\0\13\52\1\223\5\52\1\0\2\52\14\0"+
    "\1\52\30\0\1\224\30\0\1\225\67\0\1\226\26\0"+
    "\1\227\41\0\2\52\1\0\1\52\1\0\2\52\1\230"+
    "\16\52\1\0\2\52\14\0\1\52\2\0\2\52\1\0"+
    "\1\52\1\0\3\52\1\231\15\52\1\0\2\52\14\0"+
    "\1\52\2\0\2\52\1\0\1\52\1\0\3\52\1\232"+
    "\15\52\1\0\2\52\14\0\1\52\2\0\2\52\1\0"+
    "\1\52\1\0\12\52\1\56\6\52\1\0\2\52\14\0"+
    "\1\52\2\0\2\52\1\0\1\52\1\0\6\52\1\233"+
    "\12\52\1\0\2\52\14\0\1\52\23\0\1\122\46\0"+
    "\1\234\43\0\1\235\46\0\1\236\34\0\2\52\1\0"+
    "\1\52\1\0\17\52\1\70\1\52\1\0\2\52\14\0"+
    "\1\52\2\0\2\52\1\0\1\52\1\0\4\52\1\112"+
    "\14\52\1\0\2\52\14\0\1\52\2\0\2\52\1\0"+
    "\1\52\1\0\12\52\1\113\6\52\1\0\2\52\14\0"+
    "\1\52\2\0\2\52\1\0\1\52\1\0\4\52\1\237"+
    "\14\52\1\0\2\52\14\0\1\52\13\0\1\240\50\0"+
    "\1\241\63\0\1\242\21\0\2\52\1\0\1\52\1\0"+
    "\5\52\1\243\13\52\1\0\2\52\14\0\1\52\14\0"+
    "\1\244\43\0\1\245\64\0\1\124\24\0\2\52\1\0"+
    "\1\52\1\0\1\52\1\246\17\52\1\0\2\52\14\0"+
    "\1\52\10\0\1\247\54\0\1\250\34\0\2\52\1\0"+
    "\1\52\1\0\6\52\1\251\12\52\1\0\2\52\14\0"+
    "\1\52\15\0\1\252\62\0\1\253\21\0\2\52\1\0"+
    "\1\52\1\0\7\52\1\101\11\52\1\0\2\52\14\0"+
    "\1\52\30\0\1\254\43\0\1\255\47\0\1\256\46\0"+
    "\1\145\35\0\1\144\37\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6920];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\2\1\1\11\74\1\1\0\17\1\3\0"+
    "\17\1\3\0\15\1\4\0\11\1\3\0\7\1\4\0"+
    "\5\1\4\0\4\1\1\0\1\1\1\0\2\1\2\0"+
    "\1\1\2\0\1\1\2\0\1\1\5\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[174];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */

private void imprimir(String descricao) {
    System.out.print(descricao);
    MainViewController.result.append(descricao);
}



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexicalAnalyzer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 158) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
 * @return 
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Object yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { imprimir("int main(){");
            } 
            // fall through
          case 32: break;
          case 2: 
            { throw new RuntimeException("Caractere inválido " + yytext());
            } 
            // fall through
          case 33: break;
          case 3: 
            { imprimir(yytext());
            } 
            // fall through
          case 34: break;
          case 4: 
            { imprimir("&&");
            } 
            // fall through
          case 35: break;
          case 5: 
            { imprimir("=");
            } 
            // fall through
          case 36: break;
          case 6: 
            { imprimir("==");
            } 
            // fall through
          case 37: break;
          case 7: 
            { imprimir("(");
            } 
            // fall through
          case 38: break;
          case 8: 
            { imprimir(")");
            } 
            // fall through
          case 39: break;
          case 9: 
            { imprimir("+");
            } 
            // fall through
          case 40: break;
          case 10: 
            { imprimir("*");
            } 
            // fall through
          case 41: break;
          case 11: 
            { imprimir(":");
            } 
            // fall through
          case 42: break;
          case 12: 
            { imprimir("%");
            } 
            // fall through
          case 43: break;
          case 13: 
            { imprimir(">");
            } 
            // fall through
          case 44: break;
          case 14: 
            { imprimir("\n");
            } 
            // fall through
          case 45: break;
          case 15: 
            { imprimir("\t");
            } 
            // fall through
          case 46: break;
          case 16: 
            { imprimir("\t\t");
            } 
            // fall through
          case 47: break;
          case 17: 
            { imprimir(" ");
            } 
            // fall through
          case 48: break;
          case 18: 
            { imprimir("||");
            } 
            // fall through
          case 49: break;
          case 19: 
            { imprimir("if");
            } 
            // fall through
          case 50: break;
          case 20: 
            { imprimir("case");
            } 
            // fall through
          case 51: break;
          case 21: 
            { imprimir("{");
            } 
            // fall through
          case 52: break;
          case 22: 
            { imprimir("scanf");
            } 
            // fall through
          case 53: break;
          case 23: 
            { imprimir("float");
            } 
            // fall through
          case 54: break;
          case 24: 
            { imprimir("for");
            } 
            // fall through
          case 55: break;
          case 25: 
            { imprimir("else");
            } 
            // fall through
          case 56: break;
          case 26: 
            { imprimir("}");
            } 
            // fall through
          case 57: break;
          case 27: 
            { imprimir("int");
            } 
            // fall through
          case 58: break;
          case 28: 
            { imprimir("switch");
            } 
            // fall through
          case 59: break;
          case 29: 
            { imprimir("printf");
            } 
            // fall through
          case 60: break;
          case 30: 
            { imprimir("char");
            } 
            // fall through
          case 61: break;
          case 31: 
            { imprimir("while");
            } 
            // fall through
          case 62: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
