/* The following code was generated by JFlex 1.7.0 */

package model.services;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>C:/Users/tomas/Documents/eclipse-workspace-javaFX/projetoAutomatos/src/model/services/language.lex</tt>
 */
public class LexicalAnalyzer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\44\1\43\1\45\1\45\1\5\22\0\1\5\4\0\1\41"+
    "\2\0\1\34\1\35\1\37\1\36\1\3\1\27\2\0\1\6\11\2"+
    "\1\40\1\0\1\32\1\33\1\42\2\0\32\1\4\0\1\1\1\0"+
    "\1\15\1\1\1\11\1\1\1\23\1\13\1\17\1\30\1\7\2\1"+
    "\1\16\1\14\1\10\1\12\1\24\1\25\1\20\1\22\1\21\1\26"+
    "\1\31\4\1\1\0\1\4\10\0\1\45\u1fa2\0\1\45\1\45\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\2\3\2\4\10\3\1\5\1\3\2\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\4\3\1\20\4\3\1\21\2\3\1\5\21\3"+
    "\1\5\4\3\1\22\1\20\1\3\1\0\1\23\1\24"+
    "\1\25\1\3\1\21\4\3\1\26\5\3\3\0\3\3"+
    "\1\27\1\23\4\3\1\1\4\3\1\30\3\0\12\3"+
    "\1\31\2\3\4\0\3\3\1\32\1\33\2\3\1\34"+
    "\1\3\3\0\1\30\1\35\5\3\4\0\5\3\4\0"+
    "\4\3\1\0\1\30\1\0\2\30\2\0\1\3\2\0"+
    "\1\3\2\0\1\3\5\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[174];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\46\0\114\0\162\0\230\0\276\0\46\0\344"+
    "\0\u010a\0\u0130\0\u0156\0\u017c\0\u01a2\0\u01c8\0\u01ee\0\u0214"+
    "\0\u023a\0\u0260\0\u0286\0\u02ac\0\u02d2\0\u02f8\0\u031e\0\u0344"+
    "\0\u036a\0\u0390\0\u03b6\0\u03dc\0\u0402\0\u0428\0\u044e\0\u0474"+
    "\0\u049a\0\u04c0\0\u04e6\0\u050c\0\u0532\0\u0558\0\u057e\0\u05a4"+
    "\0\u05ca\0\u05f0\0\u0616\0\u063c\0\u0662\0\u0688\0\u06ae\0\u06d4"+
    "\0\u06fa\0\u0720\0\u0746\0\u076c\0\u0792\0\u07b8\0\u07de\0\u0804"+
    "\0\u082a\0\u0850\0\u0876\0\u089c\0\u08c2\0\u08e8\0\u090e\0\u0934"+
    "\0\u095a\0\u0980\0\u09a6\0\u09cc\0\u09f2\0\u0a18\0\u0a3e\0\u0a64"+
    "\0\u0a8a\0\u0ab0\0\u0ad6\0\u0afc\0\u0b22\0\u0b48\0\u0b6e\0\u0b94"+
    "\0\u0bba\0\u0be0\0\u0c06\0\u0c2c\0\u0c52\0\u0c78\0\u0c9e\0\u0cc4"+
    "\0\u0cea\0\u0d10\0\u0d36\0\u0d5c\0\u0d82\0\u0da8\0\u0dce\0\u0df4"+
    "\0\u0e1a\0\u0e40\0\u0e66\0\u0e8c\0\u0eb2\0\u0ed8\0\u0efe\0\u0f24"+
    "\0\u0f4a\0\u0f70\0\u0f96\0\u0fbc\0\u0fe2\0\u1008\0\u102e\0\u1054"+
    "\0\u107a\0\u10a0\0\u10c6\0\u10ec\0\u1112\0\u1138\0\u115e\0\u1184"+
    "\0\u11aa\0\u11d0\0\u11f6\0\u121c\0\u1242\0\u1268\0\u128e\0\u12b4"+
    "\0\u12da\0\u1300\0\u1326\0\u134c\0\u1372\0\u1398\0\u13be\0\u13e4"+
    "\0\u140a\0\u1430\0\u1456\0\u147c\0\u14a2\0\u14c8\0\u14ee\0\u1514"+
    "\0\u153a\0\u1560\0\u1586\0\u15ac\0\u15d2\0\u15f8\0\u161e\0\u1644"+
    "\0\u166a\0\u1690\0\u16b6\0\u16dc\0\u1702\0\u1728\0\u174e\0\u1774"+
    "\0\u179a\0\u17c0\0\u17e6\0\u180c\0\u1832\0\u1858\0\u187e\0\u18a4"+
    "\0\u18ca\0\u18f0\0\u1916\0\u193c\0\u1962\0\u1988";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[174];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\2\1\5\1\6\1\7\1\10"+
    "\1\3\1\11\1\12\1\13\2\3\1\14\1\3\1\15"+
    "\1\3\1\16\1\17\1\20\2\3\1\21\2\3\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\50\0\2\34\1\0\1\34\1\0\21\34"+
    "\1\0\2\34\16\0\1\4\3\0\1\4\40\0\2\34"+
    "\1\0\1\35\1\6\21\34\1\0\2\34\11\0\2\6"+
    "\5\0\2\6\35\0\2\6\2\0\2\34\1\0\1\34"+
    "\1\0\2\34\1\36\16\34\1\0\2\34\15\0\2\34"+
    "\1\0\1\34\1\0\7\34\1\37\11\34\1\0\2\34"+
    "\15\0\2\34\1\0\1\34\1\0\20\34\1\40\1\0"+
    "\2\34\15\0\2\34\1\0\1\34\1\0\1\34\1\41"+
    "\5\34\1\42\11\34\1\0\2\34\15\0\2\34\1\0"+
    "\1\34\1\0\15\34\1\43\3\34\1\0\2\34\15\0"+
    "\2\34\1\0\1\34\1\0\15\34\1\44\3\34\1\0"+
    "\2\34\15\0\2\34\1\0\1\34\1\0\15\34\1\45"+
    "\3\34\1\0\2\34\15\0\2\34\1\0\1\34\1\0"+
    "\2\34\1\46\11\34\1\47\1\50\3\34\1\0\2\34"+
    "\15\0\2\34\1\0\1\34\1\0\7\34\1\51\11\34"+
    "\1\0\2\34\43\0\1\21\2\0\1\21\46\0\1\22"+
    "\46\0\1\23\46\0\1\24\46\0\1\25\46\0\1\26"+
    "\46\0\1\27\46\0\1\30\46\0\1\31\7\0\2\6"+
    "\35\0\1\32\1\6\5\0\2\6\35\0\1\6\1\33"+
    "\2\0\2\52\1\53\1\34\1\0\21\52\1\0\2\52"+
    "\6\0\1\53\6\0\2\52\1\53\1\35\1\6\21\52"+
    "\1\0\2\52\6\0\1\53\2\0\2\6\2\0\2\52"+
    "\1\53\1\34\1\0\1\52\1\54\11\52\1\55\5\52"+
    "\1\0\2\52\6\0\1\53\6\0\2\52\1\53\1\34"+
    "\1\0\12\52\1\56\1\52\1\57\4\52\1\0\2\52"+
    "\6\0\1\53\6\0\2\52\1\53\1\34\1\0\4\52"+
    "\1\60\14\52\1\0\2\52\6\0\1\53\6\0\2\52"+
    "\1\53\1\34\1\0\6\52\1\61\12\52\1\0\2\52"+
    "\6\0\1\53\6\0\2\52\1\53\1\34\1\0\3\52"+
    "\1\62\15\52\1\0\2\52\6\0\1\53\6\0\2\52"+
    "\1\53\1\34\1\0\1\52\1\63\17\52\1\0\2\52"+
    "\6\0\1\53\6\0\2\52\1\53\1\34\1\0\7\52"+
    "\1\64\11\52\1\0\2\52\6\0\1\53\6\0\2\52"+
    "\1\53\1\34\1\0\2\52\1\65\11\52\1\66\4\52"+
    "\1\0\2\52\6\0\1\53\6\0\2\52\1\53\1\34"+
    "\1\0\13\52\1\67\3\52\1\70\1\52\1\0\2\52"+
    "\6\0\1\53\6\0\2\52\1\53\1\34\1\0\3\52"+
    "\1\71\15\52\1\0\2\52\6\0\1\53\6\0\2\52"+
    "\1\53\1\34\1\0\15\52\1\72\3\52\1\0\2\52"+
    "\6\0\1\53\6\0\2\52\1\53\1\34\1\0\12\52"+
    "\1\73\6\52\1\0\2\52\6\0\1\53\6\0\2\52"+
    "\1\0\1\52\1\0\21\52\1\0\2\52\17\0\2\53"+
    "\33\0\1\53\6\0\2\52\1\0\1\52\1\0\3\52"+
    "\1\74\15\52\1\0\2\52\15\0\2\52\1\0\1\52"+
    "\1\0\15\52\1\75\3\52\1\0\2\52\15\0\2\52"+
    "\1\0\1\52\1\0\7\52\1\76\11\52\1\0\2\52"+
    "\15\0\2\52\1\0\1\52\1\0\4\52\1\77\14\52"+
    "\1\0\2\52\15\0\2\52\1\0\1\52\1\0\20\52"+
    "\1\100\1\0\2\52\15\0\2\52\1\0\1\52\1\0"+
    "\7\52\1\101\11\52\1\102\2\52\15\0\2\52\1\0"+
    "\1\52\1\0\7\52\1\103\11\52\1\0\2\52\15\0"+
    "\2\52\1\0\1\52\1\0\7\52\1\104\11\52\1\0"+
    "\2\52\15\0\2\52\1\0\1\52\1\0\10\52\1\105"+
    "\10\52\1\0\2\52\15\0\2\52\1\0\1\52\1\0"+
    "\7\52\1\106\11\52\1\0\2\52\15\0\2\52\1\0"+
    "\1\52\1\0\15\52\1\107\3\52\1\0\2\52\15\0"+
    "\2\52\1\0\1\52\1\0\7\52\1\110\11\52\1\0"+
    "\2\52\15\0\2\52\1\0\1\52\1\0\20\52\1\111"+
    "\1\0\2\52\15\0\2\52\1\0\1\52\1\0\4\52"+
    "\1\112\5\52\1\113\6\52\1\0\2\52\15\0\2\52"+
    "\1\0\1\52\1\0\15\52\1\72\3\52\1\0\2\52"+
    "\15\0\2\52\1\0\1\52\1\0\7\52\1\114\11\52"+
    "\1\0\2\52\15\0\2\52\1\0\1\52\1\0\1\52"+
    "\1\115\17\52\1\0\2\52\15\0\2\52\1\0\1\52"+
    "\1\0\1\52\1\116\17\52\1\0\2\52\15\0\2\52"+
    "\1\0\1\52\1\0\3\52\1\117\15\52\1\0\2\52"+
    "\15\0\2\52\1\0\1\52\1\0\3\52\1\120\15\52"+
    "\1\0\2\52\15\0\2\52\1\0\1\52\1\0\4\52"+
    "\1\60\14\52\1\0\2\52\15\0\2\52\1\0\1\52"+
    "\1\0\10\52\1\121\10\52\1\0\2\52\36\0\1\122"+
    "\1\123\1\124\22\0\2\52\1\0\1\52\1\0\5\52"+
    "\1\125\13\52\1\0\2\52\15\0\2\52\1\0\1\52"+
    "\1\0\10\52\1\126\10\52\1\0\2\52\15\0\2\52"+
    "\1\0\1\52\1\0\12\52\1\127\6\52\1\0\2\52"+
    "\15\0\2\52\1\0\1\52\1\0\4\52\1\130\14\52"+
    "\1\0\2\52\15\0\2\52\1\0\1\52\1\0\14\52"+
    "\1\66\4\52\1\0\2\52\15\0\2\52\1\0\1\52"+
    "\1\0\4\52\1\131\14\52\1\0\2\52\15\0\2\52"+
    "\1\0\1\52\1\0\7\52\1\132\11\52\1\0\2\52"+
    "\15\0\2\52\1\0\1\52\1\0\10\52\1\133\10\52"+
    "\1\0\2\52\15\0\2\52\1\0\1\52\1\0\15\52"+
    "\1\134\3\52\1\0\2\52\15\0\2\52\1\0\1\52"+
    "\1\0\16\52\1\135\2\52\1\0\2\52\15\0\2\52"+
    "\1\0\1\52\1\0\4\52\1\136\14\52\1\0\2\52"+
    "\15\0\2\52\1\0\1\52\1\0\12\52\1\137\6\52"+
    "\1\0\2\52\15\0\2\52\1\0\1\52\1\0\13\52"+
    "\1\140\5\52\1\0\2\52\15\0\2\52\1\0\1\52"+
    "\1\0\7\52\1\141\11\52\1\0\2\52\15\0\2\52"+
    "\1\0\1\52\1\0\11\52\1\142\7\52\1\0\2\52"+
    "\37\0\1\143\32\0\1\144\11\0\1\145\40\0\1\146"+
    "\31\0\2\52\1\0\1\52\1\0\7\52\1\147\11\52"+
    "\1\0\2\52\15\0\2\52\1\0\1\52\1\0\15\52"+
    "\1\150\3\52\1\0\2\52\15\0\2\52\1\0\1\52"+
    "\1\0\15\52\1\151\3\52\1\0\2\52\15\0\2\52"+
    "\1\0\1\52\1\0\14\52\1\152\4\52\1\0\2\52"+
    "\15\0\2\52\1\0\1\52\1\0\15\52\1\153\3\52"+
    "\1\0\2\52\15\0\2\52\1\0\1\52\1\0\2\52"+
    "\1\154\16\52\1\0\2\52\15\0\2\52\1\0\1\52"+
    "\1\0\21\52\1\0\1\155\1\52\15\0\2\52\1\0"+
    "\1\52\1\0\21\52\1\0\1\52\1\156\15\0\2\52"+
    "\1\0\1\52\1\0\7\52\1\157\11\52\1\0\2\52"+
    "\15\0\2\52\1\0\1\52\1\0\1\52\1\160\17\52"+
    "\1\0\2\52\15\0\2\52\1\0\1\52\1\0\4\52"+
    "\1\161\14\52\1\0\2\52\15\0\2\52\1\0\1\52"+
    "\1\0\15\52\1\162\3\52\1\0\2\52\15\0\2\52"+
    "\1\0\1\52\1\0\14\52\1\57\4\52\1\0\2\52"+
    "\15\0\2\52\1\0\1\52\1\0\4\52\1\163\14\52"+
    "\1\0\2\52\27\0\1\164\57\0\1\165\31\0\1\166"+
    "\54\0\1\167\26\0\2\52\1\0\1\52\1\0\3\52"+
    "\1\62\15\52\1\0\2\52\15\0\2\52\1\0\1\52"+
    "\1\0\1\52\1\63\17\52\1\0\2\52\15\0\2\52"+
    "\1\0\1\52\1\0\7\52\1\64\11\52\1\0\2\52"+
    "\15\0\2\52\1\0\1\52\1\0\15\52\1\170\3\52"+
    "\1\0\2\52\15\0\2\52\1\0\1\52\1\0\2\52"+
    "\1\171\16\52\1\0\2\52\15\0\2\52\1\0\1\52"+
    "\1\0\13\52\1\172\5\52\1\0\2\52\15\0\2\52"+
    "\1\0\1\52\1\0\7\52\1\173\11\52\1\0\2\52"+
    "\15\0\2\52\1\0\1\52\1\0\7\52\1\174\11\52"+
    "\1\0\2\52\15\0\2\52\1\0\1\52\1\0\12\52"+
    "\1\73\6\52\1\0\2\52\15\0\2\52\1\0\1\52"+
    "\1\0\2\52\1\175\16\52\1\0\2\52\15\0\2\52"+
    "\1\0\1\52\1\0\1\52\1\176\17\52\1\0\2\52"+
    "\15\0\2\52\1\0\1\52\1\0\12\52\1\177\6\52"+
    "\1\0\2\52\15\0\2\52\1\0\1\52\1\0\12\52"+
    "\1\200\6\52\1\0\2\52\23\0\1\201\64\0\1\202"+
    "\31\0\1\203\50\0\1\204\31\0\2\52\1\0\1\52"+
    "\1\0\2\52\1\65\16\52\1\0\2\52\15\0\2\52"+
    "\1\0\1\52\1\0\13\52\1\67\5\52\1\0\2\52"+
    "\15\0\2\52\1\0\1\52\1\0\4\52\1\205\14\52"+
    "\1\0\2\52\15\0\2\52\1\0\1\52\1\0\15\52"+
    "\1\206\3\52\1\0\2\52\15\0\2\52\1\0\1\52"+
    "\1\0\15\52\1\207\3\52\1\0\2\52\15\0\2\52"+
    "\1\0\1\52\1\0\1\52\1\54\17\52\1\0\2\52"+
    "\15\0\2\52\1\0\1\52\1\0\2\52\1\210\16\52"+
    "\1\0\2\52\15\0\2\52\1\0\1\52\1\0\3\52"+
    "\1\211\15\52\1\0\2\52\15\0\2\52\1\0\1\52"+
    "\1\0\1\52\1\212\17\52\1\0\2\52\30\0\1\213"+
    "\46\0\1\214\46\0\1\215\42\0\1\216\33\0\2\52"+
    "\1\0\1\52\1\0\15\52\1\217\3\52\1\0\2\52"+
    "\15\0\2\52\1\0\1\52\1\0\14\52\1\220\4\52"+
    "\1\0\2\52\15\0\2\52\1\0\1\52\1\0\14\52"+
    "\1\221\4\52\1\0\2\52\15\0\2\52\1\0\1\52"+
    "\1\0\13\52\1\55\5\52\1\0\2\52\15\0\2\52"+
    "\1\0\1\52\1\0\7\52\1\222\11\52\1\0\2\52"+
    "\15\0\2\52\1\0\1\52\1\0\13\52\1\223\5\52"+
    "\1\0\2\52\43\0\1\224\26\0\1\225\65\0\1\226"+
    "\24\0\1\227\37\0\2\52\1\0\1\52\1\0\2\52"+
    "\1\230\16\52\1\0\2\52\15\0\2\52\1\0\1\52"+
    "\1\0\3\52\1\231\15\52\1\0\2\52\15\0\2\52"+
    "\1\0\1\52\1\0\3\52\1\232\15\52\1\0\2\52"+
    "\15\0\2\52\1\0\1\52\1\0\12\52\1\56\6\52"+
    "\1\0\2\52\15\0\2\52\1\0\1\52\1\0\6\52"+
    "\1\233\12\52\1\0\2\52\36\0\1\122\44\0\1\234"+
    "\41\0\1\235\44\0\1\236\32\0\2\52\1\0\1\52"+
    "\1\0\17\52\1\70\1\52\1\0\2\52\15\0\2\52"+
    "\1\0\1\52\1\0\4\52\1\112\14\52\1\0\2\52"+
    "\15\0\2\52\1\0\1\52\1\0\12\52\1\113\6\52"+
    "\1\0\2\52\15\0\2\52\1\0\1\52\1\0\4\52"+
    "\1\237\14\52\1\0\2\52\26\0\1\240\46\0\1\241"+
    "\61\0\1\242\17\0\2\52\1\0\1\52\1\0\5\52"+
    "\1\243\13\52\1\0\2\52\27\0\1\244\41\0\1\245"+
    "\62\0\1\124\22\0\2\52\1\0\1\52\1\0\1\52"+
    "\1\246\17\52\1\0\2\52\23\0\1\247\52\0\1\250"+
    "\32\0\2\52\1\0\1\52\1\0\6\52\1\251\12\52"+
    "\1\0\2\52\30\0\1\252\60\0\1\253\17\0\2\52"+
    "\1\0\1\52\1\0\7\52\1\101\11\52\1\0\2\52"+
    "\43\0\1\254\41\0\1\255\45\0\1\256\44\0\1\145"+
    "\33\0\1\144\35\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6574];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\4\1\1\11\72\1\1\0\17\1\3\0"+
    "\17\1\3\0\15\1\4\0\11\1\3\0\7\1\4\0"+
    "\5\1\4\0\4\1\1\0\1\1\1\0\2\1\2\0"+
    "\1\1\2\0\1\1\2\0\1\1\5\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[174];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */

private void imprimir(String descricao) {
    System.out.print(descricao);
}



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexicalAnalyzer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 152) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
 * @return 
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Object yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { imprimir("int main(){");
            } 
            // fall through
          case 30: break;
          case 2: 
            { throw new RuntimeException("Caractere inválido " + yytext());
            } 
            // fall through
          case 31: break;
          case 3: 
            { imprimir(yytext());
            } 
            // fall through
          case 32: break;
          case 4: 
            { imprimir(" ");
            } 
            // fall through
          case 33: break;
          case 5: 
            { imprimir("&&");
            } 
            // fall through
          case 34: break;
          case 6: 
            { imprimir("=");
            } 
            // fall through
          case 35: break;
          case 7: 
            { imprimir("(");
            } 
            // fall through
          case 36: break;
          case 8: 
            { imprimir(")");
            } 
            // fall through
          case 37: break;
          case 9: 
            { imprimir("+");
            } 
            // fall through
          case 38: break;
          case 10: 
            { imprimir("*");
            } 
            // fall through
          case 39: break;
          case 11: 
            { imprimir(":");
            } 
            // fall through
          case 40: break;
          case 12: 
            { imprimir("%");
            } 
            // fall through
          case 41: break;
          case 13: 
            { imprimir(">");
            } 
            // fall through
          case 42: break;
          case 14: 
            { imprimir("\n");
            } 
            // fall through
          case 43: break;
          case 15: 
            { imprimir("\t");
            } 
            // fall through
          case 44: break;
          case 16: 
            { imprimir("||");
            } 
            // fall through
          case 45: break;
          case 17: 
            { imprimir("if");
            } 
            // fall through
          case 46: break;
          case 18: 
            { imprimir("case");
            } 
            // fall through
          case 47: break;
          case 19: 
            { imprimir("{");
            } 
            // fall through
          case 48: break;
          case 20: 
            { imprimir("scanf");
            } 
            // fall through
          case 49: break;
          case 21: 
            { imprimir("float");
            } 
            // fall through
          case 50: break;
          case 22: 
            { imprimir("for");
            } 
            // fall through
          case 51: break;
          case 23: 
            { imprimir("else");
            } 
            // fall through
          case 52: break;
          case 24: 
            { imprimir("}");
            } 
            // fall through
          case 53: break;
          case 25: 
            { imprimir("int");
            } 
            // fall through
          case 54: break;
          case 26: 
            { imprimir("switch");
            } 
            // fall through
          case 55: break;
          case 27: 
            { imprimir("printf");
            } 
            // fall through
          case 56: break;
          case 28: 
            { imprimir("char");
            } 
            // fall through
          case 57: break;
          case 29: 
            { imprimir("while");
            } 
            // fall through
          case 58: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
